#!/bin/sh

/bin/busybox --install -s /bin

date `cat /buildtime` > /dev/null

mount -t devtmpfs /dev /dev
mount -a

mkdir -p /dev/pts /var/run /var/log /var/lock

syslogd

hostname -F /etc/hostname
mount -t devpts /dev/pts /dev/pts

#Run twice, because new devices found after initial module load
find /sys/ -name modalias | xargs sort -u | xargs -n 1 modprobe 2> /dev/null
find /sys/ -name modalias | xargs sort -u | xargs -n 1 modprobe 2> /dev/null

ifconfig lo up 127.0.0.1

/etc/init.d/rcS-local
