#!/bin/sh

/bin/busybox --install -s /bin

date `cat /buildtime` > /dev/null

mount -t devtmpfs /dev /dev
mount -a

mkdir -p /dev/pts /var/run /var/log /var/lock

syslogd

hostname -F /etc/hostname
mount -t devpts /dev/pts /dev/pts

#Run 3 times, because new devices found after initial module load
/usr/bin/detect_kmods 2> /dev/null
sleep 1
/usr/bin/detect_kmods 2> /dev/null
sleep 1
/usr/bin/detect_kmods 2> /dev/null

ifconfig lo up 127.0.0.1

/etc/init.d/rcS-local

echo ""
echo -n "Welcome to "
cat /etc/karls_version
