#!/bin/sh

#Kernel parameter, hardcoded into isolinux and grub in iso image
if [ "$KARLS_MEDIA" == "ISO" ]; then
 echo "Booting from ISO"

 /etc/init.d/rcS-mount_iso
 #Try a 4th (!!!) module load round after 3 secs, if ISO not found / maybe it's a slow USB
 if [ ! -e "/mnt/iso/karls_iso" ]; then
  sleep 3
  /etc/init.d/rcS-detect_kmods 2> /dev/null
  /etc/init.d/rcS-mount_iso
 fi
 #If ISO is found, setup system for install
 if [ -e "/mnt/iso/karls_iso" ]; then
  if [ -e "/mnt/iso/install/setup" ]; then
   echo "#!/bin/sh" > /bin/setup
   echo ". /mnt/iso/install/setup" >> /bin/setup
   chmod 755 /bin/setup
   /bin/setup
  fi
 else
  echo "Install media not found!"
  cat /etc/version
 fi
fi
