#!/bin/sh

mkdir -p /dev/pts
mount -t devpts -o nosuid,noexec devpts /dev/pts

hostname -F /etc/hostname

syslogd

ifconfig lo up 127.0.0.1

KARLS=`cat /etc/karls_version`
echo ""
echo "Welcome to $KARLS Initrd System"
