#!/bin/sh

tar -C / -xJf /mnt/iso/packages/musl-1.2.5.txz
tar -C / -xJf /mnt/iso/packages/grub-2.12.txz

KARLS=`cat /mnt/iso/karls_iso`
echo ""
echo "Welcome to $KARLS Installation/Live ISO"

while true; do
echo ""
echo "Press Any Key to start Installation or \"S\" to drop to Live ISO Shell"
read -s -n 1
REP=`echo $REPLY | tr '[:upper:]' '[:lower:]'`
if [ "$REP" == "s" ]; then
 exit 0
fi
echo ""
echo "                        * * * WARNING * * *"
echo ""
echo "Installing KarLS on a disk will DESTROY all other data on that disk!"
echo ""
echo "Possible installation target candidates:"
fdisk -l | grep Disk
echo ""
echo -n "Enter device to install: "
read
if [ ! -b "$REPLY" ]; then
 echo "[$REPLY] not found or not a device!"
 continue
fi
TRGT="$REPLY"
echo ""
echo "Insallation target is [$TRGT]!"
fdisk -l $TRGT
echo ""
echo "             * * * LAST CHANCE! Do you really want to continue? * * *"
echo ""
echo "KarLS will be installed on [$TRGT], and all pre-existing data will be destroyed there!"
echo ""
echo -n "Type \"CONTINUE\" to continue installation: "
read
if [ "$REPLY" != "CONTINUE" ]; then
 echo "Installation cancelled!"
 continue
fi

echo "Partitioning disk..."
echo -e "o\nn\np\n1\n2048\n\na\n1\nw\n" | fdisk $TRGT > /dev/null
ret=$?
if [ $ret -ne 0 ]; then
 echo "fdisk error, installation cancelled!"
 break
fi

echo "Formatting ext2 partition..."
mkfs.ext2 "$TRGT"1 > /dev/null
ret=$?
if [ $ret -ne 0 ]; then
 echo "mkfs.ext2 error, installation cancelled!"
 break
fi

echo "Mounting target..."
mkdir -p /mnt/target
mount "$TRGT"1 /mnt/target > /dev/null
if [ $ret -ne 0 ]; then
 echo "mount error, installation cancelled!"
 break
fi

echo "Copying boot files..."
mkdir -p /mnt/target/boot/grub
cp /mnt/iso/boot/karls.krnl \
/mnt/iso/boot/initrd.gz \
/mnt/iso/boot/System.map \
/mnt/target/boot
mkdir -p /mnt/target/lib
cp -r /lib/modules /mnt/target/lib

echo "Installing GRUB boot loader..."
grub-install --boot-directory=/mnt/target/boot "$TRGT"
if [ $ret -ne 0 ]; then
 echo "grub-install error, installation cancelled!"
 break
fi
cp /mnt/iso/install/grub.cfg /mnt/target/boot/grub

echo "Installation finished!"
echo "Press Ctrl-Alt-Delete or type \"reboot\" in shell to reboot!"
break
done
