#!/bin/sh

#Kernel parameter, hardcoded into isolinux and grub in iso image
if [ "$KARLS_MEDIA" == "ISO" ]; then
 /etc/init.d/rcS-mount_iso
 #Try a 4th (!!!) module load round after 3 secs, if ISO not found / maybe it's a slow USB
 if [ ! -e "/mnt/iso/karls_iso" ]; then
  sleep 3
  /etc/init.d/rcS-detect_kmods 2> /dev/null
  /etc/init.d/rcS-mount_iso
 fi
 #If ISO is found, setup system for install
 if [ -e "/mnt/iso/install/setup" ]; then
  . /mnt/iso/install/setup
 fi
fi
