#!/bin/sh

/bin/busybox --install -s /bin

mount -t devtmpfs /dev /dev
mount -a

mkdir -p /dev/pts /var/run /var/log /var/lock

mount -t devpts /dev/pts /dev/pts

#Run 3 times, because new devices found after initial module load
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null

[[ "$KARLS_MEDIA" == "ISO" ]] && echo Booting from ISO

exec /bin/init <dev/console >dev/console 2>&1
