#!/bin/sh

/bin/busybox --install -s /bin

mount -t devtmpfs /dev /dev
#Mount fstab - /proc /sys /tmp
mount -a

mkdir -p /dev/pts /tmp/var/run /tmp/var/log /tmp/var/lock

mount -t devpts /dev/pts /dev/pts

#Run 3 times, because new devices found after initial module load
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null

#Check if we can find a rootfs then try to mount it
ROOTUUID=`cat /proc/cmdline | tr ' ' '\n' | grep root= | cut -d= -f2`
[[ ! -z "$ROOTUUID" ]] && ROOTDISK=`blkid | grep $ROOTUUID | cut -d: -f1`

if [ -b "$ROOTDISK" ]; then
 mkdir /newroot
 mount -o ro $ROOTDISK /newroot
 ret=$?
 [[ $ret -ne 0 ]] && echo "Could not mount root FS!"
fi

exec /bin/init <dev/console >dev/console 2>&1
