#!/bin/sh

/bin/busybox --install -s /bin

mount -t devtmpfs -o nosuid devtmpfs /dev
#Mount fstab - /proc /sys
mount -a

#Run 3 times, because new devices found after initial module load
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null
sleep 1
/etc/init.d/rcS-detect_kmods 2> /dev/null

exec /bin/init <dev/console >dev/console 2>&1
