#!/bin/sh

mkdir -p /dev/pts
#Mount remaining filesystems - devpts, /tmp, etc.
mount -a

hostname -F /etc/hostname

syslogd

ifconfig lo up 127.0.0.1

KARLS=`cat /etc/karls_version`
echo ""
echo "Welcome to $KARLS"
