#!/bin/sh

start()
{
mkdir -p /var/spool/cron/crontabs
crond -l 5
echo crond started
}

stop()
{
[[ -f "/var/run/crond.pid" ]] && kill `cat /var/run/crond.pid`
rm -f /var/run/crond.*
echo crond stopped
}

. /etc/init.d/parse
