#!/bin/sh

start()
{
mkdir -p /var/log
syslogd -b 10
echo syslogd started
}

stop()
{
[[ -f "/var/run/syslogd.pid" ]] && kill `cat /var/run/syslogd.pid`
rm -f /var/run/syslogd.*
echo syslogd stopped
}

. /etc/init.d/parse
